"use client";

import { useEffect, useState } from "react";
import { Metric, Notice, PageIntro, Section } from "@/components/ui";
import { money, number, request } from "@/lib/api";

type Group = { city: string; n: number; mae: number; rmse: number; mean_residual: number; coverage: number };
type Fairness = { by_city: Group[]; ablation: { with_city_cv_rmse: number; without_city_cv_rmse: number; delta_rmse: number }; limitation: string };

export default function FairnessPage() {
  const [data, setData] = useState<Fairness | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { request<Fairness>("/reports/fairness").then(setData).catch(e => setError(e.message)); }, []);
  return <><PageIntro kicker="05 / Responsible ML" title="Audit model behavior by city">Compare held-out errors and interval coverage across geographic groups. Sample sizes stay visible so variation can be interpreted in context.</PageIntro>{error ? <Notice kind="error">{error}</Notice> : !data ? <Notice>Loading geographic diagnostics…</Notice> : <><Section label="Subgroup diagnostics" title="Errors and coverage by city"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>City</th><th>Test candidates</th><th>MAE</th><th>RMSE</th><th>Mean residual</th><th>90% interval coverage</th></tr></thead><tbody>{data.by_city.map(row => <tr key={row.city}><td><strong>{row.city}</strong></td><td>{row.n}</td><td>{money(row.mae)}</td><td>{money(row.rmse)}</td><td className={row.mean_residual >= 0 ? "positive" : "negative"}>{row.mean_residual >= 0 ? "+" : "−"}{money(Math.abs(row.mean_residual))}</td><td>{number(row.coverage*100,1)}%</td></tr>)}</tbody></table></div><p className="small-note top-space">Residual = actual minus predicted, INR/year. The conformal interval targets 90% marginal coverage, not guaranteed 90% coverage in each city.</p></Section><Section label="City ablation" title="Does city improve prediction?"><div className="metrics-strip"><Metric label="With city · CV RMSE" value={money(data.ablation.with_city_cv_rmse)} /><Metric label="Without city · CV RMSE" value={money(data.ablation.without_city_cv_rmse)} /><Metric label="Difference" value={`${data.ablation.delta_rmse >= 0 ? "+" : "−"}${money(Math.abs(data.ablation.delta_rmse))}`} /></div><p className="top-space">Both models use the same family and five training folds. This measures predictive contribution, not a causal city effect.</p></Section><Section label="Limits" title="What this audit cannot establish"><Notice>{data.limitation}</Notice><p className="top-space">The dataset is generated by an explicit salary process and does not contain gender, caste, religion, disability, or other protected-class labels. These diagnostics do not establish demographic fairness or real-world validity.</p></Section></>}</>;
}
